(function(){
  const year=document.getElementById('year'); if(year) year.textContent=new Date().getFullYear();
  const toggle=document.getElementById('menuToggle'); const nav=document.getElementById('navPrincipal');
  if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));}
  const revealEls=document.querySelectorAll('.reveal');
  if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});revealEls.forEach(el=>io.observe(el));}else revealEls.forEach(el=>el.classList.add('visible'));
  const sections=[...document.querySelectorAll('main section[id]')]; const navLinks=[...document.querySelectorAll('.nav a')];
  if('IntersectionObserver'in window){const nio=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}})},{rootMargin:'-40% 0px -52%'});sections.forEach(s=>nio.observe(s));}
  const form=document.getElementById('cotizacionForm'); const error=document.getElementById('formError'); const summary=document.getElementById('seleccionResumen');
  document.querySelectorAll('.quote-product').forEach(btn=>btn.addEventListener('click',()=>{const val=btn.dataset.product;const boxes=[...document.querySelectorAll('input[name="Interes"]')];const box=boxes.find(b=>b.value===val);if(box)box.checked=true;document.getElementById('contacto').scrollIntoView({behavior:'smooth'});setTimeout(()=>{const first=form?.querySelector('input[name="Nombre"]');first?.focus({preventScroll:true})},550)}));
  if(form) form.addEventListener('submit',e=>{const selected=[...form.querySelectorAll('input[name="Interes"]:checked')];if(!selected.length){e.preventDefault();error.textContent='Seleccione al menos un producto o servicio de interés.';form.querySelector('fieldset').scrollIntoView({behavior:'smooth',block:'center'});return;}error.textContent='';summary.value=selected.map(x=>x.value).join(', ');});
})();
